version: "3"
services:
  worker:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 16M
      restart_policy:
        condition: any
        delay: 5s
    ports:
      - 56700:56700 # LIFX listener
    image: chrisns/lifx-mqtt
    command: "--host ${MQTT_SERVICE_IP} --lifx-broadcast ${LIFX_SUBNET} --subscription /home/lights --on-bulb bulb-found --on-light-status bulb-state-change --on-new-light new-bulb-found --on-connect-topic connected-lifx-bridge"